export const CHOOSE_CATEGORY = "CHOOSE_CATEGORY"
export const LOAD_ITEMS_BY_CATEGORY = "LOAD_ITEMS_BY_CATEGORY"
export const NORMALIZE_SUB_CATEGORIES_BY_CATEGORY = "NORMALIZE_SUB_CATEGORIES_BY_CATEGORY"
export const NORMALIZE_ITEMS_BY_CATEGORY = "NORMALIZE_ITEMS_BY_CATEGORY"
